# config/rbac/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-cluster-role
rules:
  # Allow the webhook to get, list, and watch CRDs
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]

  # Allow the webhook to work with the admission API
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]

  # Allow access to ClusterExtension resources
  - apiGroups: ["olm.operatorframework.io"]
    resources: ["clusterextensions"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
