apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-deployment
  labels:
    app: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      serviceAccountName: webhook-service-account
      containers:
        - name: webhook
          image: localhost/webhook:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: webhook-certs
              mountPath: /certs
              readOnly: true
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: api-key
      volumes:
        - name: webhook-certs
          secret:
            secretName: webhook-certs
