apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-deployment
  labels:
    app: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      hostNetwork: true
      serviceAccountName: webhook-service-account
      containers:
        - name: webhook
          image: localhost/webhook:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: webhook-certs
              mountPath: /certs
              readOnly: true
          env:
            - name: LOCAL_LLM_URL
              value: "http://34.47.23.99:8001/v1/chat/completions"
      volumes:
        - name: webhook-certs
          secret:
            secretName: webhook-certs
